### ISSUE TITLE
[stable] Broken import in qcs_api_client.models

### ISSUE THREAD

**Issue by drewrisinger** [rigetti/qcs-api-client-python#4]
When importing anything from ``qcs_api_client.models`` on v0.20.14, it fails here: https://github.com/rigetti/qcs-api-client-python/blob/163099cda954def653c47f970b6b33e8654d2027/qcs_api_client/models/__init__.py#L3

This is because apparently the ``qcs_api_client.models.account_balance`` module was removed. This problem exists on both the source release of v0.20.14 & the PyPi release.

Full error message:
```
  File "/nix/store/lvw14vwzdasnpg19l4hy2wz2s4rrrdvb-python3.8-qcs-api-client-0.20.14/lib/python3.8/site-packages/qcs_api_client/models/__init__.py", line 3, in <module>
    from .account_balance import AccountBalance
ModuleNotFoundError: No module named 'qcs_api_client.models.account_balance'
```

**Comment by erichulburd** [comment]
@drewrisinger We have released 0.20.17 where the issue is resolved. We have also yanked the versions with missing files.
